exclude = [
    "https?://(dx\\.)?doi\\.org/.*",
    "https?://(www\\.)?ilo\\.org/.*",
    "https?://(www\\.)?ohchr\\.org/.*",
    "https?://(www\\.)?unicef\\.org/.*",
# Denmark
    "https?://(www\\.)?ft\\.dk/.*",
# France
    "https?://(www\\.)?legifrance\\.gouv\\.fr/.*",
# Jersey
    "https?://(www\\.)?itv\\.com/.*",
# Kyrgystan
    "cbd\\.minjust\\.gov\\.kg",
# Northern Territory
    "https?://(www\\.)?nt\\.gov\\.au/.*",
# Togo
    "https?://(www\\.)?assemblee\\-nationale\\.tg/.*"
]
